= backup(3)
:doctype: manpage
:manmanual: Manual for libsimplegba
:mansource: libsimplegba
:revdate: 2025-07-11
:docdate: {revdate}

== NAME
backup_init, backup_read, backup_write, backup_read_byte,
backup_write_byte, backup_identify, backup_set_bank, backup_erase_chip,
backup_erase_sector - backup memory

== SYNOPSIS
[verse]
____
*#include <libsimplegba.h>*

**void backup_init(const void +++*+++**__driver__**);**

**void backup_read(u16 **__offset__**, void +++*+++**__buffer__**, u32 **__n__**);**
**void backup_write(u16 **__offset__**, const void +++*+++**__buffer__**, u32 **__n__**);**

**i32 backup_read_byte(u16 **__offset__**);**
**void backup_write_byte(u16 **__offset__**, i32 **__byte__**);**

*u16 backup_identify(void);*
**void backup_set_bank(u32 **__bank__**);**

*void backup_erase_chip(void);*
**void backup_erase_sector(u32 **__n__**);**
____

== DESCRIPTION
The *backup_init*() function initializes the specified _driver_. This
function should only be called once. Based on the backup chip being
used, _driver_ should be either *BACKUP_SRAM* or *BACKUP_FLASH*.

The *backup_read*() and *backup_write*() functions, respectively, read
from and write to backup memory, transferring _n_ bytes between _buffer_
and the backup memory area starting at _offset_.

The *backup_read_byte*() function reads one unsigned byte from backup
memory at address _offset_ and returns it. The *backup_write_byte*()
function writes _byte_ into backup memory at address _offset_.

=== Flash ROM functions
These functions are specific to the Flash ROM driver. When called in
other drivers, they perform no operation. Unlike other memory chips,
Flash ROM must be erased before writing to it.

The *backup_identify*() reads the chip's 16-bit identification
code and returns it.

The *backup_set_bank*() function switches the chip's bank to the value
of _bank_. This function should only be used on chips of size 128 KB,
and the value of _bank_ should be either 0 or 1.

The *backup_erase_chip*() function erases all data in the chip. The
*backup_erase_sector*() function erases the 4 KB sector of index _n_.
The value of _n_ should be in the range [0, 15] and, for 128 KB chips,
the erased sector also depends on the currently selected bank. Erased
bytes are set to 255 (0xff).

== RETURN VALUE
The *backup_read_byte*() function returns the byte read from backup
memory.

The *backup_identify*() function returns the Flash ROM chip's 16-bit
identification code.

== AUTHORS
The *libsimplegba* library was written by Vulcalien
<\vulcalien@vulcalien.net>.
