= backup_sram(3)
:doctype: manpage
:manmanual: Manual for libsimplegba
:mansource: libsimplegba
:revdate: 2024-08-01
:docdate: {revdate}

== NAME
backup_sram_read, backup_sram_write, backup_sram_read_byte,
backup_sram_write_byte - SRAM backup memory functions

== SYNOPSIS
[verse]
____
*#include <gba/backup.h>*

**void backup_sram_read(u16 **__offset__**, void +++*+++**__buffer__**, u32 **__n__**);**
**void backup_sram_write(u16 **__offset__**, const void +++*+++**__buffer__**, u32 **__n__**);**

**u8 backup_sram_read_byte(u16 **__address__**);**
**void backup_sram_write_byte(u16 **__address__**, u8 **__byte__**);**
____

== DESCRIPTION
The *backup_sram_read*() and *backup_sram_write*() functions,
respectively, read from and write to backup memory. These functions
transfer _n_ bytes between _buffer_ and the backup memory area beginning
at _offset_.

The *backup_sram_read_byte*() function reads one byte from backup memory
at address _offset_ and returns it. The *backup_sram_write_byte*()
function writes _byte_ into backup memory at address _offset_.

== RETURN VALUE
The *backup_sram_read_byte*() function returns the byte read from backup
memory.

== AUTHORS
The *libsimplegba* library was written by Vulcalien
<\vulcalien@vulcalien.net>.
