= display(3)
:doctype: manpage
:manmanual: Manual for libsimplegba
:mansource: libsimplegba
:revdate: 2025-07-16
:docdate: {revdate}

== NAME
display_config, display_force_blank, display_charblock,
display_screenblock, display_get_page, display_set_page,
display_get_raster - display functions

== SYNOPSIS
[verse]
____
*#include <libsimplegba.h>*

*#define DISPLAY_WIDTH  240*
*#define DISPLAY_HEIGHT 160*

**void display_config(u32 **__video_mode__**);**
**void display_force_blank(bool **__flag__**);**

**vu16 +++*+++display_charblock(i32 **__block__**);**
**vu16 +++*+++display_screenblock(i32 **__block__**);**

**i32  display_get_page(void);**
**void display_set_page(i32 **__page__**);**
**vu16 +++*+++display_get_raster(i32 **__page__**);**
____

== DESCRIPTION
=== Display configuration
The *display_config*() function sets the __video_mode__ of the display.
The video mode determines how the display is drawn and how video memory
is allocated. The __video_mode__ argument can be any of the
*DISPLAY_MODE_x* constants, with *x* replaced by the video mode number.

Video modes 0-2 use tiled backgrounds (tilemaps). Which backgrounds are
available, and how they are treated (regular or affine), depend on the
video mode selected. Charblocks are allocated as follows: 0-3 background
tilesets, 4-5 sprite tileset.

.Tilemap video modes
[cols="1,1,1,1,1"]
|===

|*Mode* |*BG0* |*BG1* |*BG2* |*BG3*
|0      |reg   |reg   |reg   |reg
|1      |reg   |reg   |aff   |
|2      |      |      |aff   |aff
|===

Video modes 3-5 use bitmaps. The size, BPP (bits-per-pixel), and number
of pages depend on the video mode selected. Charblocks are allocated as
follows: 0-4 raster, 5 sprite tileset.

.Bitmap video modes
[cols="1,1,1,1"]
|===

|*Mode* |*Size*  |*BPP* |*Pages*
|3      |240x160 |16    |1
|4      |240x160 |8     |2
|5      |160x128 |16    |2
|===

The *display_force_blank*() function enables or disables forced blank,
based on the value of _flag_. When forced blank is enabled, all pixels
of the display are set to white.

=== Video memory
The *display_charblock*() function returns a pointer to the charblock of
index _block_. Charblocks are 16 KB areas of video memory used to store
tilesets. See *display_config*() to see how charblocks are allocated.
The value of _block_ should be in the range [0, 5].

The *display_screenblock*() function returns a pointer to the
screenblock of index _block_. Screenblocks are 2 KB areas of video
memory used to store tilemaps. The value of _block_ should be in the
range [0, 31].

=== Display pages (bitmap modes only)
The *display_get_page*() function returns the index of the display page
currently being shown. The *display_set_page*() function sets the
display page to show to _page_.

The *display_get_raster*() function returns a pointer to the raster of
the specified _page_. The raster is an array of colors, with size and
bits-per-pixel that depend on the video mode.

== NOTES
Video memory should only be written to using 16-bit or 32-bit writes.

== AUTHORS
The *libsimplegba* library was written by Vulcalien
<\vulcalien@vulcalien.net>.
