= input(3)
:doctype: manpage
:manmanual: Manual for libsimplegba
:mansource: libsimplegba
:revdate: 2025-01-10
:docdate: {revdate}

== NAME
input_update, input_down, input_pressed, input_released,
input_irq_config - input detection

== SYNOPSIS
[verse]
____
*#include <gba/input.h>*

*void input_update(void);*

**bool input_down(u16 **__key__**);**
**bool input_pressed(u16 **__key__**);**
**bool input_released(u16 **__key__**);**

**void input_irq_config(bool **__all_keys__**, u16 **__keys__**);**
____

== DESCRIPTION
The *input_update*() function updates the module's internal state to
match the one of the GBA buttons. This function should be called once at
the beginning of every tick (game update), before any input processing
is done.

The *input_down*(), *input_pressed*() and *input_released*() functions
return true if the specified _key_ is currently in the matching state
(i.e. down, pressed, released). _key_ can be any of the constants listed
below.

.Key identifiers
[cols="1,1,1,1"]
|===

|KEY_A     |KEY_B    |KEY_SELECT |KEY_START
|KEY_RIGHT |KEY_LEFT |KEY_UP     |KEY_DOWN
|KEY_R     |KEY_L    |           |
|===

The *input_irq_config*() function configures the keypad interrupt
condition. If __all_keys__ is true, the interrupt is raised if all of
the specified keys are down at the same time; if __all_keys__ is false,
the interrupt is raised if any of those keys is down. The _keys_
argument is a list of keys joined together using the bitwise OR operator
(e.g., *KEY_A* | *KEY_START*). For the interrupt to be acknowledged, it
must also be enabled by calling the *interrupt_toggle*(3) function
passing *IRQ_KEYPAD* as argument.

== RETURN VALUE
The *input_down*(), *input_pressed*() and *input_released*() functions
return true if the specified _key_ is currently in the matching state,
false otherwise.

== AUTHORS
The *libsimplegba* library was written by Vulcalien
<\vulcalien@vulcalien.net>.

== SEE ALSO
*interrupt_toggle*(3), *interrupt_set_isr*(3)
