= interrupt(3)
:doctype: manpage
:manmanual: Manual for libsimplegba
:mansource: libsimplegba
:revdate: 2024-05-02
:docdate: {revdate}

== NAME
interrupt_init, interrupt_enable, interrupt_disable, interrupt_set_isr -
interrupt driver functions

== SYNOPSIS
[verse]
____
*#include "interrupt.h"*

*void interrupt_init(void);*

**void interrupt_enable(u8 **__irq__**);**
**void interrupt_disable(u8 **__irq__**);**

**void interrupt_set_isr(u8 **__irq__**, void (+++*+++**__isr__**)(void));**
____

== DESCRIPTION
The *interrupt_init*() function initializes the driver. This needs to be
called once before calling other functions of the interrupt driver or
any module that depends on the interrupt driver (such as the sound
driver).

The *interrupt_enable*() and *interrupt_disable()* functions enable and
disable the specified _irq_, identified by one of the constants listed
below.

.IRQ identifiers
[cols="1,1,1,1"]
|===

|IRQ_VBLANK |IRQ_HBLANK  |IRQ_VCOUNT |
|IRQ_TIMER0 |IRQ_TIMER1  |IRQ_TIMER2 |IRQ_TIMER3
|IRQ_DMA0   |IRQ_DMA1    |IRQ_DMA2   |IRQ_DMA3
|IRQ_KEYPAD |IRQ_GAMEPAK |IRQ_SERIAL |
|===

The *interrupt_set_isr*() function maps the specified _irq_ to its _isr_
(Interrupt Service Routine). _irq_ can be any of the interrupt
identifiers listed above.

If _irq_ is NULL, the driver will perform no action when that interrupt
is detected. It is recommended (but not required) to also disable the
interrupt by calling *interrupt_disable*().

== NOTES
Each IRQ can be mapped to just one ISR at a time, so calling
*interrupt_set_isr*() will overwrite the previous association. If
multiple ISRs are required, the recommended approach is to write a
function that calls all the others:

[source,c]
----
void foo_isr(void) {
    foo_isr_a();
    foo_isr_b();
}
----

== EXAMPLES
Enable the VBLANK interrupt and map an ISR to it:

[source,c]
----
int AgbMain(void) {
    interrupt_init();

    interrupt_enable(IRQ_VBLANK);
    interrupt_set_isr(IRQ_VBLANK, vblank_isr);
}
----

== AUTHORS
The *libsimplegba* library was written by Vulcalien
<\vulcalien@vulcalien.net>.
