= interrupt(3)
:doctype: manpage
:manmanual: Manual for libsimplegba
:mansource: libsimplegba
:revdate: 2025-01-10
:docdate: {revdate}

== NAME
interrupt_toggle, interrupt_set_isr - interrupt handling

== SYNOPSIS
[verse]
____
*#include <gba/interrupt.h>*

**void interrupt_toggle(u32 **__irq__**, bool **__enable__**);**
**void interrupt_set_isr(u32 **__irq__**, void (+++*+++**__isr__**)(void));**
____

== DESCRIPTION
The *interrupt_toggle*() function enables or disables (depending on the
value of _enable_) the specified _irq_, identified by one of the
constants listed below.

.IRQ identifiers
[cols="1,1,1,1"]
|===

|IRQ_VBLANK |IRQ_HBLANK  |IRQ_VCOUNT |
|IRQ_TIMER0 |IRQ_TIMER1  |IRQ_TIMER2 |IRQ_TIMER3
|IRQ_DMA0   |IRQ_DMA1    |IRQ_DMA2   |IRQ_DMA3
|IRQ_KEYPAD |IRQ_GAMEPAK |IRQ_SERIAL |
|===

The *interrupt_set_isr*() function maps the specified _irq_ to its _isr_
(Interrupt Service Routine). If _isr_ is set to NULL, no action will be
performed when that interrupt is raised.

== NOTES
Each IRQ can only be mapped to one ISR at a time, so that calling
*interrupt_set_isr*() overwrites the previous association. If an IRQ
needs multiple ISRs, the recommended approach is to write a wrapper
function:

[source,c]
----
void foo_isr(void) {
    foo_isr_a();
    foo_isr_b();
}
----

== EXAMPLES
Enable the VBlank interrupt and map an ISR to it:

[source,c]
----
int AgbMain(void) {
    interrupt_toggle(IRQ_VBLANK, true);
    interrupt_set_isr(IRQ_VBLANK, vblank_isr);
}
----

== AUTHORS
The *libsimplegba* library was written by Vulcalien
<\vulcalien@vulcalien.net>.
