= libsimplegba(7)
:doctype: manpage
:manmanual: Manual for libsimplegba
:mansource: libsimplegba
:revdate: 2025-03-27
:docdate: {revdate}

== NAME
libsimplegba - overview of libsimplegba

== DESCRIPTION
This library offers functions and constants useful when interfacing with
hardware components of the Game Boy Advance, plus some other utilities.

The library contains two files needed for compilation: _lnkscript_
(linker script) and _crt0.s_ (startup code).

[verse]
____
Modules included in this library (and corresponding headers):
    Misc
        Base                *<base.h>*
        Math                *<math.h>*
        Random              *<random.h>*
        Memory              *<memory.h>*

    GBA Hardware
        Display             *<gba/display.h>*
        Background          *<gba/background.h>*
        Sprite              *<gba/sprite.h>*
        Window              *<gba/window.h>*
        Audio               *<gba/audio.h*
        Timer               *<gba/timer.h>*
        DMA                 *<gba/dma.h>*
        Input               *<gba/input.h>*
        Interrupt           *<gba/interrupt.h>*
        System              *<gba/system.h>*
        Cartridge           *<gba/cartridge.h>*
        Backup              *<gba/backup.h>*

    Debug
        Profiler            *<debug/profiler.h>*
        mGBA                *<debug/mgba.h>*
____

=== Misc

*Base <base.h>*::
Basic definitions, such as data types (u8, i32, bool...), their MIN/MAX
constants (*I32_MIN*, *U16_MAX*...), the NULL pointer, section macros
(*IWRAM_SECTION*, *SBSS_SECTION*...), etc.

*Math <math.h>*::
Various mathematical functions for integers and fixed-point numbers,
including basic trigonometry.

*Random <random.h>*::
Pseudorandom number generator, offering the _random_ function and other
related functions.

*Memory <memory.h>*::
Memory manipulation, including replacements for _memset_ and _memcpy_,
plus alignment-specific versions of them.

=== GBA Hardware

*Display <gba/display.h>*::
Basic display functions, such as configuring the Video Mode or getting a
pointer to the bitmap raster. Graphic effects are also included.

*Background <gba/background.h>*::
Configure and interact with the GBA display's background layers.

*Sprite <gba/sprite.h>*::
Configure and interact with the GBA display's sprites.

*Window <gba/window.h>*::
Configure the GBA display's windows.

*Audio <gba/audio.h>*::
Play digital audio on independent channels, with options to loop, change
volume and change panning.

*Timer <gba/timer.h>*::
Interface with the GBA's hardware timers.

*DMA <gba/dma.h>*::
Configure and interact with the GBA's four DMA channels, using them to
make memory transfers.

*Input <gba/input.h>*::
Interface with the GBA's buttons and D-Pad.

*Interrupt <gba/interrupt.h>*::
Enable or disable interrupt requests and set callback functions (ISRs)
that handle those requests.

*System <gba/system.h>*::
System control interface, including constants such as the GBA's clock
frequency.

*Cartridge <gba/cartridge.h>*::
Access information about the cartridge, such as its header.

*Backup <gba/backup.h>*::
Transfer data between memory and the cartridge's backup chip.

=== Debug

*Profiler <debug/profiler.h>*::
Profile a piece of code, obtaining an indicative count of the CPU clock
cycles required to run it.

*mGBA <debug/mgba.h>*::
Interface with the debug registers of the mGBA emulator, allowing to
print text similarly to how the standard output is used in computer
programs.

== AUTHORS
The *libsimplegba* library was written by Vulcalien
<\vulcalien@vulcalien.net>.
