= libsimplegba(7)
:doctype: manpage
:manmanual: Manual for libsimplegba
:mansource: libsimplegba
:revdate: 2025-07-12
:docdate: {revdate}

== NAME
libsimplegba - overview of libsimplegba

== DESCRIPTION
*libsimplegba* offers interfaces for hardware components of the Game Boy
Advance, as well as basic utilities such as math and memory functions.
The library also contains audio drivers, some debugging tools, and files
needed to compile ROMs.

[verse]
____
The following modules are available:
    Misc
        Base                basic definitions (types, macros...)
        Math                various mathematical functions
        Random              pseudo-random number generator
        Memory              memory manipulation

    GBA Hardware
        Display             display interface
        Background          tiled backgrounds
        Sprite              sprites
        Window              display windows (e.g. viewports)
        Audio               digital audio driver
        Timer               hardware timers
        DMA                 direct memory access
        Input               input detection
        Interrupt           interrupt handling
        System              system control
        Cartridge           game cartridge
        Backup              backup memory

    Debug
        Profiler            code profiler
        mGBA                printing to mGBA output (e.g. mgba_printf)
____

Most of the library modules are accompanied by a manual: read them for
details about the functionalities offered by each module.

=== Usage
Add the 'include' directory to the include path and the 'bin' directory
to the library search path, then link against 'libsimplegba' and set
'lnkscript' as the linker script. If using a Makefile, add the following
lines (replacing <path> with the path to the library):

[source,make]
----
# linker script
LDFLAGS += -nostartfiles -T<path>/lnkscript

# libsimplegba
CPPFLAGS += -I<path>/include
LDFLAGS  += -L<path>/bin
LDLIBS   += -lsimplegba
----

The library expects the *AgbMain*() function as entry point of the
program. This function takes no arguments and returns nothing.

TODO define ROM header

== AUTHORS
The *libsimplegba* library was written by Vulcalien
<\vulcalien@vulcalien.net>.
