= math(3)
:doctype: manpage
:manmanual: Manual for libsimplegba
:mansource: libsimplegba
:revdate: 2024-06-12
:docdate: {revdate}

== NAME
math_min, math_max, math_abs, math_sign, math_pow, math_sqrt, math_sin,
math_cos - various mathematical functions

== SYNOPSIS
[verse]
____
*#include "math.h"*

**i32 math_min(i32 **__a__**, i32 **__b__**);**
**i32 math_max(i32 **__a__**, i32 **__b__**);**

**i32 math_abs(i32 **__val__**);**
**i32 math_sign(i32 **__val__**);**

**i32 math_pow(i32 **__base__**, u32 **__exp__**);**
**u16 math_sqrt(u32 **__val__**);**

*#define MATH_PI 0x8000*

**i16 math_sin(u16 **__angle__**);**
**i16 math_cos(u16 **__angle__**);**
____

== DESCRIPTION
The *math_min*() and *math_max*() functions return, respectively, the
minimum and maximum between the two values _a_ and _b_.

The *math_abs*() function returns the absolute value of _val_. If _val_
is the most negative 32-bit integer (*I32_MIN*), the result of this
function is undefined.

The *math_sign*() function returns +1 if _val_ is positive, -1 if _val_
is negative and 0 if _val_ is zero.

The *math_pow*() function returns the value of _base_ to the power of
_exp_. If _exp_ is 0, the result is always 1. Since this function
calculates an integer power, _base_ is allowed to be negative. If _base_
to the power of _exp_ does not fit within a signed 32-bit integer, the
result is undefined.

The *math_sqrt*() function returns the integral part (i.e., floor) of
the square root of _val_.

=== Trigonometry
The trigonometric functions in this module use binary radians (brad) to
measure angles. The value of PI is defined in the *MATH_PI* constant.

The *math_sin*() and *math_cos*() functions return, respectively,
approximate values of sine and cosine of _angle_. The returned value is
an integer in the range [-0x4000, 0x4000], with the lower and upper
bounds (both included) representing -1 and +1.

== NOTES
The result of *math_pow*(0, 0) is 1.

While the _angle_ parameter of the *math_sin*() and *math_cos*()
functions is an unsigned 16-bit integer, in practice these functions can
also take negative angles and work as expected due to integer overflow.

== AUTHORS
The *libsimplegba* library was written by Vulcalien
<\vulcalien@vulcalien.net>.
