= profiler(3)
:doctype: manpage
:manmanual: Manual for libsimplegba
:mansource: libsimplegba
:revdate: 2025-04-13
:docdate: {revdate}

== NAME
profiler_start, profiler_stop - code profiler

== SYNOPSIS
[verse]
____
*#include <debug/profiler.h>*

*void profiler_start(void);*
*u32  profiler_stop(void);*
____

== DESCRIPTION
The *profiler_start*() function must be called before the piece of code
being examined is executed.

The *profiler_stop*() function returns an indicative count of CPU clock
cycles elapsed since the last call to *profiler_start*(). The returned
value is not perfectly accurate because a few cycles necessary to
execute the *profiler_start*() and *profiler_stop*() functions
themselves will be counted as well.

== RETURN VALUE
The *profiler_stop*() function returns an indicative count of CPU clock
cycles elapsed since the last call to *profiler_start*().

== NOTES
These profiler functions use two of the GBA's timers: Timer 2 and
Timer 3. For the profiler to work, these two timers must not be in use
while profiling.

== EXAMPLES
Measure the time needed to execute the two functions foo() and bar():

[source,c]
----
int AgbMain(void) {
    profiler_start();

    foo();
    bar();

    u32 time = profiler_stop();
}
----

== AUTHORS
The *libsimplegba* library was written by Vulcalien
<\vulcalien@vulcalien.net>.
