= random(3)
:doctype: manpage
:manmanual: Manual for libsimplegba
:mansource: libsimplegba
:revdate: 2025-02-18
:docdate: {revdate}

== NAME
random, random_seed - pseudo-random number generator

== SYNOPSIS
[verse]
____
*#include <random.h>*

*#define RANDOM_MAX 65535*

**i32 random(u32 **__bound__**);**
**u32 random_seed(u32 **__seed__**);**
____

== DESCRIPTION
The *random*() function returns a pseudo-random integer uniformly
distributed between 0 and _bound_ (exclusive). The _bound_ argument must
be in the range [1, *RANDOM_MAX* + 1].

The *random_seed*() function sets _seed_ as the new generator's seed and
returns the previously stored seed value.

== RETURN VALUE
The *random*() function returns a pseudo-random integer uniformly
distributed between 0 and _bound_ (exclusive).

The *random_seed*() function returns the previously stored seed value as
a _u32_ (unsigned 32-bit integer).

== NOTES
If *random*() is called with a _bound_ of 1, the function always returns
0.

== AUTHORS
The *libsimplegba* library was written by Vulcalien
<\vulcalien@vulcalien.net>.
