= sprite(3)
:doctype: manpage
:manmanual: Manual for libsimplegba
:mansource: libsimplegba
:revdate: 2024-11-12
:docdate: {revdate}

== NAME
sprite_config, sprite_hide, sprite_hide_range, sprite_hide_all,
sprite_mosaic, sprite_affine - sprite functions

== SYNOPSIS
[verse]
____
*#include <gba/sprite.h>*

*#define SPRITE_COUNT 128*

**void sprite_config(u32 **__id__**, const struct Sprite +++*+++**__sprite__**);**

**void sprite_hide(u32 **__id__**);**
**void sprite_hide_range(u32 **__start__**, u32 **__stop__**);**
*void sprite_hide_all(void);*

**void sprite_mosaic(u32 **__x__**, u32 **__y__**);**
**void sprite_affine(u32 **__parameter__**, i16 **__matrix__**[4]);**
____

== DESCRIPTION
Some of these functions take an _id_ parameter, or a range of IDs. These
identify which sprites to operate on. There are *SPRITE_COUNT* (128)
sprites available.

=== Sprite configuration
The *sprite_config*() function configures the sprite with the settings
specified in the _config_ structure. The structure is defined as
follows:

[source,c]
----
struct Sprite {
    u32 x : 9;
    u32 y : 8;

    u32 disable  : 1;
    u32 mode     : 2;
    u32 priority : 2;

    u32 size : 4;
    u32 flip : 2;

    u32 tile    : 10;
    u32 palette : 4;

    u32 mosaic : 1;
    u32 colors : 1;

    u32 affine           : 1;
    u32 affine_parameter : 5;
    u32 double_size      : 1;
};
----

The _x_ and _y_ fields specify the location of the sprite's top-left
corner, relative to the display's top-left corner. These values are
treated as signed integers.

The _disable_ field specifies whether a sprite is hidden (one) or not
(zero). If set to one, this has the same effect as calling
*sprite_hide*() on the same sprite ID. Ignored if _affine_ is one.

The _mode_ field TODO

The _priority_ field TODO

The _size_ field specifies the size of the sprite. Its value can be any
of the *SPRITE_SIZE_X* constants, with *X* replaced by one of the
following sizes:

.Sprite sizes
[cols="1,1,1,1,1"]
|===

|*Square*     |8x8  |16x16 |32x32 |64x64
|*Horizontal* |16x8 |32x8  |32x16 |64x32
|*Vertical*   |8x16 |8x32  |16x32 |32x64
|===

The _flip_ field specifies if and how the sprite is flipped. Ignored if
_affine_ is one. Possible values are: *SPRITE_FLIP_NONE* (0),
*SPRITE_FLIP_HORIZONTAL* (1), *SPRITE_FLIP_VERTICAL* (2),
*SPRITE_FLIP_BOTH* (3).

The _tile_ field TODO

The _palette_ field TODO

The _mosaic_ field specifies whether the mosaic graphic effect is
applied to the sprite. See *sprite_mosaic*().

The _colors_ field specifies the color mode of the sprite. TODO

The _affine_ field specifies whether an affine transformation is applied
to the sprite (one) or not (zero).

The __affine_parameter__ field specifies which of the 32 affine
transformation matrices is used to transform the sprite. Use
*sprite_affine*() to set the values of these matrices. Ignored if
_affine_ is zero.

The __double_size__ field specifies whether the sprite size is doubled
while applying an affine transformation (one) or not (zero). Ignored if
_affine_ is zero.

=== Hiding sprites
The *sprite_hide*() function hides the sprite identified by _id_.

The *sprite_hide_range*() function hides all sprites whose ID is between
_start_ (inclusive) and _stop_ (exclusive).

The *sprite_hide_all*() function hides all sprites.

=== Mosaic and Affine
TODO

== AUTHORS
The *libsimplegba* library was written by Vulcalien
<\vulcalien@vulcalien.net>.
