= sprite(3)
:doctype: manpage
:manmanual: Manual for libsimplegba
:mansource: libsimplegba
:revdate: 2025-07-11
:docdate: {revdate}

== NAME
sprite_config, sprite_hide, sprite_hide_range, sprite_mosaic,
sprite_affine - sprite functions

== SYNOPSIS
[verse]
____
*#include <libsimplegba.h>*

**void sprite_config(i32 **__id__**, const struct Sprite +++*+++**__sprite__**);**

**void sprite_hide(i32 **__id__**);**
**void sprite_hide_range(i32 **__start__**, i32 **__stop__**);**

**void sprite_mosaic(u32 **__x__**, u32 **__y__**);**
**void sprite_affine(u32 **__parameter__**, i16 **__matrix__**[4]);**
____

== DESCRIPTION
Sprites, also called objects, are graphical elements that can be drawn
anywhere on the display, without being restricted to a grid like
background tiles are. There are *SPRITE_COUNT* (128) sprites.

=== Sprite configuration
The *sprite_config*() function configures the sprite with the settings
specified in the _config_ structure. The structure is defined as
follows:

[source,c]
----
struct Sprite {
    u32 x : 9;
    u32 y : 8;

    u32 disable  : 1;
    u32 mode     : 2;
    u32 priority : 2;

    u32 size : 4;
    u32 flip : 2;

    u32 tile    : 10;
    u32 palette : 4;

    u32 mosaic : 1;
    u32 colors : 1;

    u32 affine           : 1;
    u32 affine_parameter : 5;
    u32 double_size      : 1;
};
----

The _x_ and _y_ fields specify the position of the sprite's top-left
corner relative to the display. These values are treated as signed
integers.

The _disable_ field specifies whether a sprite is hidden or not. If set
to one, this has the same effect as calling *sprite_hide*() on the same
sprite ID. Ignored if _affine_ is one.

The _mode_ field specifies the sprite's mode. Possible values are:
*SPRITE_MODE_NORMAL*, *SPRITE_MODE_SEMI_TRANSPARENT*,
*SPRITE_MODE_WINDOW*.

The _priority_ field specifies the drawing priority of the sprite
relative to background layers. The sprite will be drawn on top of
background layers with a priority value *higher than or equal to*
_priority_. Note that sprites with lower IDs always have priority over
sprites with higher IDs, regardless of their _priority_ values.

The _size_ field specifies the size of the sprite. Its value can be any
of the *SPRITE_SIZE_x* constants, with *x* replaced by one of the
following sizes:

.Sprite sizes
|===
|*Square*     |8x8  |16x16 |32x32 |64x64
|*Horizontal* |16x8 |32x8  |32x16 |64x32
|*Vertical*   |8x16 |8x32  |16x32 |32x64
|===

The _flip_ field specifies if and how the sprite is flipped. Ignored if
_affine_ is one. Possible values are: *SPRITE_FLIP_NONE*,
*SPRITE_FLIP_HORIZONTAL*, *SPRITE_FLIP_VERTICAL*, *SPRITE_FLIP_BOTH*.

The _tile_ field specifies the top-left tile number, thus selecting the
image used to draw the sprite. The range of this value is affected by
the display's video mode (see *display_config*(3)) and by the sprite's
color mode (determined by the _colors_ field). See NOTES below.

.Tile value ranges
|===
|                |*16-color mode* |*256-color mode*
|*Tilemap modes* |0-1023 (1024)   |0-511 (512)
|*Bitmap modes*  |512-1023 (512)  |256-511 (256)
|===

The _palette_ field specifies which 16-color row of the sprite palette
is used to draw the sprite. Ignored if _colors_ is one (256-color mode).

The _mosaic_ field specifies whether the mosaic graphic effect is
applied to the sprite. See *sprite_mosaic*().

The _colors_ field specifies the color mode of the sprite, determining
how VRAM data for its tiles is interpreted. In 16-color mode pixels are
mapped to one 16-color row of the sprite palette, while in 256-color
mode pixels are mapped to the entire sprite palette. Possible values
are: *SPRITE_COLORS_16*, *SPRITE_COLORS_256*.

The _affine_ field specifies whether an affine transformation is applied
to the sprite or not.

The __affine_parameter__ field specifies which of the 32 affine
transformation matrices is used to transform the sprite. Use
*sprite_affine*() to set the values of these matrices. Ignored if
_affine_ is zero.

The __double_size__ field specifies whether the sprite size is doubled
while applying an affine transformation or not. Ignored if _affine_ is
zero.

=== Hiding sprites
The *sprite_hide*() function hides the sprite identified by _id_, or all
sprites if a negative value is passed.

The *sprite_hide_range*() function hides all sprites whose ID is between
_start_ (inclusive) and _stop_ (exclusive).

=== Mosaic and Affine
The *sprite_mosaic*() function sets the parameters of the mosaic graphic
effect of sprites. TODO

The *sprite_affine*() function sets the values of the affine matrix
identified by _parameter_ (0 to 31). The 2x2 matrix describes an affine
transformation used for *inverse texture mapping*. Its values are signed
16-bit fixed-point numbers, with 8 bits as fractional part (1 = 256).

== NOTES
If a sprite uses 256-color mode, each tile occupies double the amount of
VRAM, meaning that only half the tiles are available. Bitmap video modes
use charblock 4 to display pixels, meaning that only the second half of
the tiles is available.

== AUTHORS
The *libsimplegba* library was written by Vulcalien
<\vulcalien@vulcalien.net>.
