= sprite(3)
:doctype: manpage
:manmanual: Manual for libsimplegba
:mansource: libsimplegba
:revdate: 2024-10-30
:docdate: {revdate}

== NAME
sprite_config, sprite_hide, sprite_hide_range, sprite_hide_all,
sprite_mosaic, sprite_affine - sprite functions

== SYNOPSIS
[verse]
____
*#include <gba/sprite.h>*

*#define SPRITE_COUNT 128*

**void sprite_config(u32 **__id__**, const struct Sprite +++*+++**__sprite__**);**

**void sprite_hide(u32 **__id__**);**
**void sprite_hide_range(u32 **__start__**, u32 **__stop__**);**
*void sprite_hide_all(void);*

**void sprite_mosaic(u32 **__x__**, u32 **__y__**);**
**void sprite_affine(u32 **__parameter__**, i16 **__matrix__**[4]);**
____

== DESCRIPTION
Some of these functions take an _id_ parameter, or a range of IDs. These
identify which sprites to operate on. There are *SPRITE_COUNT* sprites
available.

=== Sprite configuration
The *sprite_config*() function configures the sprite with the settings
specified in the _config_ structure.

TODO

=== Hiding sprites
The *sprite_hide*() function hides the sprite identified by _id_.

The *sprite_hide_range*() function hides all sprites whose ID is between
_start_ (inclusive) and _stop_ (exclusive).

The *sprite_hide_all*() function hides all sprites.

=== Mosaic and Affine
TODO

== AUTHORS
The *libsimplegba* library was written by Vulcalien
<\vulcalien@vulcalien.net>.
