= timer(3)
:doctype: manpage
:manmanual: Manual for libsimplegba
:mansource: libsimplegba
:revdate: 2024-06-08
:docdate: {revdate}

== NAME
timer_config, timer_start, timer_stop, timer_restart, timer_get_counter
- timer driver functions

== SYNOPSIS
[verse]
____
*#include "timer.h"*

*#define TIMER_COUNT 4*
*#define TIMER_COUNTER_MAX 65536*

**void timer_config(u32 **__id__**, u16 **__config__**);**

**void timer_start(u32 **__id__**, u32 **__ticks__**);**
**void timer_stop(u32 **__id__**);**
**void timer_restart(u32 **__id__**, u32 **__ticks__**);**

**u32 timer_get_counter(u32 **__id__**);**
____

== DESCRIPTION
All of these functions take the _id_ argument, used to identify the
timers. This can be an integer between 0 and 3 or one of these
constants: *TIMER0*, *TIMER1*, *TIMER2*, *TIMER3*.

Each timer has its decrementing counter, with values between 1 and
*TIMER_COUNTER_MAX* (defined as 65536 = 2^16). When starting a timer, an
initial counter value has to be provided. Every time a timer ticks, its
counter is decremented until it reaches zero. Once that happens, the
counter will be immediately reset to the provided initial value and the
timer will continue running.

The *timer_config*() function configures the specified timer. The
_config_ argument can be any of these constants: *TIMER_PRESCALER_1*,
*TIMER_PRESCALER_64*, *TIMER_PRESCALER_256*, *TIMER_PRESCALER_1024*,
*TIMER_CASCADE*. If _config_ is one of the prescaler constants, the
timer will tick every 1, 64, 256 or 1024 CPU cycles. If _config_ is
*TIMER_CASCADE*, the timer will tick only when the counter of the
previous timer (_id_ - 1) reaches zero. Timer 0 cannot be configured to
run in cascade mode.

The *timer_start*() function starts the specified timer and sets its
initial counter value to _ticks_. Before being started, the timer should
be properly configured by calling *timer_config*(). If the timer is
already running, this function will change the counter's initial value
without overwriting its current value.

The *timer_stop*() function stops the specified timer. Stopping a timer
does not reset its counter, nor does it affect its configuration.

The *timer_restart*() function does the same thing as *timer_start*(),
but first stops the specified timer. It is recommended to use this
function instead of *timer_start*() when the timer's state is either
running or unknown.

The *timer_get_counter*() function returns the specified timer's counter
value. Since stopping a timer does not reset its counter, it is safe to
call this function on stopped timers.

== NOTES
This library considers the timers to be decrementing (i.e., their
counters are decremented). In GBA hardware, and thus in documentation
regarding it, the timers are considered to be incrementing. When using
this driver and reading other GBA documentation, be aware of this
difference.

== AUTHORS
The *libsimplegba* library was written by Vulcalien
<\vulcalien@vulcalien.net>.
