= timer(3)
:doctype: manpage
:manmanual: Manual for libsimplegba
:mansource: libsimplegba
:revdate: 2025-07-11
:docdate: {revdate}

== NAME
timer_config, timer_start, timer_stop, timer_restart, timer_get_counter
- hardware timers

== SYNOPSIS
[verse]
____
*#include <gba/timer.h>*

*#define TIMER0*
*#define TIMER1*
*#define TIMER2*
*#define TIMER3*

**void timer_config(i32 **__id__**, u16 **__config__**);**

**void timer_start(i32 **__id__**, u32 **__ticks__**);**
**void timer_stop(i32 **__id__**);**
**void timer_restart(i32 **__id__**, u32 **__ticks__**);**

**i32 timer_get_counter(i32 **__id__**);**
____

== DESCRIPTION
Timers are hardware components that precisely measure time. They are
composed of a *counter* and a *reload register*, with values between 1
and *TIMER_COUNTER_MAX* (65536). Each time a timer ticks, its counter is
decremented. When the counter reaches zero, the counter is immediately
reset to the reload value, and the timer continues running.

When the counter of a timer reaches zero, an interrupt request tied to
that timer is raised, if enabled: see *interrupt_enable(3)*.

=== Timer configuration
The *timer_config*() function configures the timer and, if running,
stops it. The _config_ argument can be any of these constants:
*TIMER_PRESCALER_1*, *TIMER_PRESCALER_64*, *TIMER_PRESCALER_256*,
*TIMER_PRESCALER_1024*, *TIMER_CASCADE*.

If configured with one of the prescaler constants, the timer ticks every
1, 64, 256 or 1024 CPU cycles. If configured to run in cascade mode, the
timer ticks only when the counter of the previous timer (_id_ - 1)
reaches zero. Timer 0 cannot be configured to run in cascade mode.

=== Timer operation
The *timer_start*() function starts the timer and sets its reload value
to _ticks_. If the timer is already running, this function only updates
its reload value, without resetting its counter. Timers should be
configured before being started.

The *timer_stop*() function stops the timer. Stopping a timer does not
affect its counter, nor does it affect its configuration.

The *timer_restart*() function restarts the timer, ensuring that its
counter is reset without waiting for it to first reach zero. This is
equivalent to stopping the timer and then starting it.

The *timer_get_counter*() function returns the timer's counter value.
Since stopping a timer does not affect its counter, it is safe to call
this function on stopped timers.

== RETURN VALUE
The *timer_get_counter*() function returns the timer's counter value, an
integer in the range [1, *TIMER_COUNTER_MAX*].

== NOTES
This library assumes timers to be *decrementing* (i.e., their counters
are decremented). Other projects and GBA documentation instead consider
timers to be *incrementing*. The two interpretations are equivalent, but
be aware of this difference when using this module and reading other GBA
documentation.

== AUTHORS
The *libsimplegba* library was written by Vulcalien
<\vulcalien@vulcalien.net>.
