= timer(3)
:doctype: manpage
:manmanual: GBA Base Library Manual
:mansource: gba-base-library
:revdate: 2024-05-06
:docdate: {revdate}

== NAME
timer_config, timer_start, timer_stop, timer_restart, timer_get_counter
- timer driver functions

== SYNOPSIS
[verse]
____
*#include "timer.h"*

*#define TIMER_COUNT 4*

**void timer_config(u32 **__id__**, const struct Timer +++*+++**__config__**);**

**void timer_start(u32 **__id__**, u32 **__ticks__**);**
**void timer_stop(u32 **__id__**);**
**void timer_restart(u32 **__id__**, u32 **__ticks__**);**

**u16 timer_get_counter(u32 **__id__**);**
____

== DESCRIPTION
All of these functions take the _id_ parameter, used to identify the
timers. This can be an integer between 0 and 3 or one of these
constants: *TIMER0*, *TIMER1*, *TIMER2*, *TIMER3*.

Each timer has its own counter, which is decremented until zero is
reached. Once that happens, the counter will be reloaded and the timer
will continue running.

The *timer_config*() function configures the specified timer with the
configuration specified in the _config_ structure. If currently running,
the specified timer will be stopped. Passing NULL as _config_ is
equivalent to passing the structure with all fields set to zero. The
structure is defined as follows:

[source,c]
----
struct Timer {
    u16 prescaler : 2; // 0=1, 1=64, 2=256, 3=1024 (number of cycles)
    u16 cascade   : 1; // 0=disable, 1=enable
    u16 irq       : 1; // 0=disable, 1=enable
};
----

The _prescaler_ field specifies how many CPU cycles are needed for the
timer to tick. The _cascade_ field, if set to one, makes the timer tick
only when the counter of the previous timer (_id_ - 1) reaches zero.
This option makes the timer ignore the _prescaler_ value and cannot be
used for Timer 0. The _irq_ field, if set to one, makes the timer raise
an interrupt request when its counter reaches zero. For the interrupt to
be acknowledged, it must also be enabled by *interrupt_enable*(3).

The *timer_start*() function starts the specified timer and sets its
counter value to _ticks_. Before being started, the timer should be
properly configured by calling *timer_config*(). If the timer is already
running, this function will set the counter's next value without
overwriting the current value.

The *timer_stop*() function stops the specified timer without affecting
its configuration. Note that stopping a timer does not reset its
counter.

The *timer_restart*() function does the same thing as *timer_start*(),
but first stops the specified timer. It is recommended to use this
function instead of *timer_start*() when the timer's state is either
running or unknown.

The *timer_get_counter*() function returns the specified timer's counter
value. Since stopping a timer does not reset its counter, it is safe to
call this function on stopped timers.

== NOTES
This driver makes it look as if the timers decrement their counters. In
the GBA hardware, and thus in documentation regarding it, these timers
actually increment their counters. When using this driver and reading
other GBA documentation, be aware of this difference.

Passing the value zero as _ticks_ argument of the *timer_start*() and
*timer_restart*() functions means that the timer's counter will be set
to 65536 (i.e., 0x10000).

== AUTHORS
The GBA Base Library was written by Vulcalien
<\vulcalien@vulcalien.net>.
