= display(3)
:doctype: manpage
:manmanual: Manual for libsimplegba
:mansource: libsimplegba
:revdate: 2026-03-26
:docdate: {revdate}

== NAME
display_config, display_charblock, display_screenblock, display_raster,
display_get_page, display_set_page - display functions

== SYNOPSIS
[verse]
____
*#include <libsimplegba.h>*

*#define DISPLAY_WIDTH  240*
*#define DISPLAY_HEIGHT 160*

**void display_config(i32 **__mode__**);**

**vu16 +++*+++display_charblock(i32 **__block__**);**
**vu16 +++*+++display_screenblock(i32 **__block__**);**

**vu16 +++*+++display_raster(i32 **__page__**);**
**i32  display_get_page(void);**
**void display_set_page(i32 **__page__**);**
____

== DESCRIPTION
=== Display configuration
The *display_config*() function sets the video _mode_ of the display.
The video mode determines how the display is drawn and how video memory
is allocated. If _mode_ is negative, all pixels are set to white. Note
that any enabled background or window is disabled, and the raster page
is set to 0.

Video modes 0-2 use tiled backgrounds (tilemaps). Which backgrounds are
available, and how they are treated (regular or affine), depend on the
video mode selected. Charblocks are allocated as follows: 0-3 background
tilesets, 4-5 sprite tileset.

.Tilemap video modes
|===
|*Mode* |*BG0* |*BG1* |*BG2* |*BG3*

|0      |reg   |reg   |reg   |reg
|1      |reg   |reg   |aff   |
|2      |      |      |aff   |aff
|===

Video modes 3-5 use bitmaps. The size, BPP (bits-per-pixel), and number
of pages depend on the video mode selected. Charblocks are allocated as
follows: 0-4 raster, 5 sprite tileset.

.Bitmap video modes
|===
|*Mode* |*Size*  |*BPP* |*Pages*

|3      |240x160 |16    |1
|4      |240x160 |8     |2
|5      |160x128 |16    |2
|===

=== Video memory
The *display_charblock*() function returns a pointer to the charblock of
index _block_. Charblocks are 16 KB areas of video memory used to store
tilesets. See *display_config*() to see how charblocks are allocated.
The value of _block_ should be in the range [0, 5].

The *display_screenblock*() function returns a pointer to the
screenblock of index _block_. Screenblocks are 2 KB areas of video
memory used to store tilemaps. The value of _block_ should be in the
range [0, 31].

=== Display pages (bitmap modes only)
The *display_raster*() function returns a pointer to the raster of the
specified _page_. The raster is an array of colors, with size and
bits-per-pixel that depend on the video mode.

The *display_get_page*() function returns the index of the display page
currently being shown. The *display_set_page*() function sets the
display page to show to _page_.

== NOTES
Video memory should only be written to using 16-bit or 32-bit writes.

== AUTHORS
The *libsimplegba* library was written by Vulcalien.
