= dma(3)
:doctype: manpage
:manmanual: Manual for libsimplegba
:mansource: libsimplegba
:revdate: 2025-07-11
:docdate: {revdate}

== NAME
dma_config, dma_transfer, dma_stop - direct memory access

== SYNOPSIS
[verse]
____
*#include <libsimplegba.h>*

*#define DMA0*
*#define DMA1*
*#define DMA2*
*#define DMA3*

**void dma_config(i32 **__id__**, const struct DMA +++*+++**__config__**);**

**void dma_transfer(i32 **__id__**, volatile void +++*+++**__dest__**,**
                  **volatile const void +++*+++**__src__**, u32 **__n__**);**

**void dma_stop(i32 **__id__**);**
____

== DESCRIPTION
=== DMA configuration
The *dma_config*() function configures the DMA channel with the settings
specified in the _config_ structure. If currently enabled, the DMA
channel will be disabled. The structure is defined as follows:

[source,c]
----
struct DMA {
    u16 dest_control : 2;
    u16 src_control  : 2;
    u16 chunk        : 1;
    u16 start_timing : 2;
    u16 repeat       : 1;
};
----

The __dest_control__ and __src_control__ fields specify how the
destination and source addresses should be modified during DMA
transfers. The addresses can be incremented, decremented or be fixed.
The destination address can also be incremented/reloaded, meaning that
it will be incremented during a DMA transfer and reset to its initial
value when the transfer repeats. These constants can be used to set the
two fields: *DMA_ADDR_INCREMENT*, *DMA_ADDR_DECREMENT*,
*DMA_ADDR_FIXED*, *DMA_ADDR_RELOAD* (__dest_control__ only).

The _chunk_ field specifies whether the DMA transfer should use 16-bit
or 32-bit chunks. These constants can be used to set the field:
*DMA_CHUNK_16_BIT*, *DMA_CHUNK_32_BIT*.

The __start_timing__ field specifies when the DMA transfer should start.
This can be immediately or when an event occurs: VBlank, HBlank or a
special event. The special event depends on the DMA channel: for DMA 0,
not allowed; for DMA 1 and DMA 2, a request to fill the sound buffer;
for DMA 3, the so-called 'Video Capture'. These constants can be used to
set the field: *DMA_START_IMMEDIATELY*, *DMA_START_VBLANK*,
*DMA_START_HBLANK*, *DMA_START_SPECIAL*.

The _repeat_ field specifies whether or not the DMA channel should
remain enabled after completing a DMA transfer. If set to one, a DMA
transfer will be made every time the start event occurs. This bit is
ignored if the start timing is 'immediately'.

=== DMA operation
The *dma_transfer*() function enables the DMA channel and sets the
initial destination address to _dest_, the initial source address to
_source_ and the number of chunks (not bytes) to transfer to _n_. Before
being enabled, The DMA channel should be properly configured by calling
*dma_config*().

The *dma_stop*() function disables the DMA channel. This operation does
not affect the channel's configuration.

== NOTES
The source and destination addresses should be properly aligned to match
the chunk size: 2-byte aligned for 16-bit chunks, 4-byte aligned for
32-bit chunks.

The DMA 0 channel can only read from internal memory. Meanwhile, the DMA
3 channel can also write to the cartridge, but for that to have any
effect there would need to be compatible hardware.

== AUTHORS
The *libsimplegba* library was written by Vulcalien
<\vulcalien@vulcalien.net>.
