= input(3)
:doctype: manpage
:manmanual: Manual for libsimplegba
:mansource: libsimplegba
:revdate: 2026-05-01
:docdate: {revdate}

== NAME
input_init, input_update, input_down, input_press, input_release,
input_repeat - input detection

== SYNOPSIS
[verse]
____
*#include <libsimplegba.h>*

**void input_init(i32 **__repeat_delay__**, i32 **__repeat_interval__**);**
**void input_update(void);**

**bool input_down(u32 **__key__**);**
**bool input_press(u32 **__key__**);**
**bool input_release(u32 **__key__**);**
**bool input_repeat(u32 **__key__**);**
____

== DESCRIPTION
The *input_init*() function initializes the module, setting repeat delay
and repeat interval to the specified values measured in update cycles.
Both values must be in the range [1, 240] and __repeat_delay__ must be
higher than or equal to __repeat_interval__.

The *input_update*() function updates the module's internal state. This
function should be called once at the beginning of every game update,
before any input processing is done.

=== Button status
These functions take the _key_ argument, used to identify GBA buttons.
This can be any of the following constants:

|===
|KEY_A     |KEY_B    |KEY_SELECT |KEY_START
|KEY_RIGHT |KEY_LEFT |KEY_UP     |KEY_DOWN
|KEY_R     |KEY_L    |           |
|===

The *input_down*() function returns true if the specified _key_ is being
held down.

The *input_press*() function returns true if the specified _key_ has
just been pressed.

The *input_release*() function returns true if the specified _key_ has
just been released.

The *input_repeat*() function returns true if the specified _key_ has
just been pressed or is being repeated. A key is repeated, with a period
equal to the repeat interval, if it has been held down for longer than
the repeat delay. See *input_init*() above.

== RETURN VALUE
The *input_down*(), *input_press*(), *input_release*() and
*input_repeat*() functions return true if the specified _key_ is
currently in the matching state, false otherwise.

== AUTHORS
The *libsimplegba* library was written by Vulcalien.
