= interrupt(3)
:doctype: manpage
:manmanual: Manual for libsimplegba
:mansource: libsimplegba
:revdate: 2026-05-01
:docdate: {revdate}

== NAME
interrupt_config, interrupt_isr, interrupt_toggle, interrupt_wait -
interrupt handling

== SYNOPSIS
[verse]
____
*#include <libsimplegba.h>*

**void interrupt_config(i32 **__id__**, i32 **__config__**);**
**void interrupt_isr(i32 **__id__**, void (+++*+++**__isr__**)(void));**

**void interrupt_toggle(i32 **__id__**, bool **__enable__**);**
**void interrupt_wait(i32 **__id__**);**
____

== DESCRIPTION
Interrupts are signals generated by specific events that pause the
normal flow of execution. Interrupts can be assigned an ISR (Interrupt
Service Routine), a function to execute right after the interrupt is
acknowledged. If an interrupt is raised while an ISR is running, the
interrupt is handled after the ISR returns.

The *interrupt_config*() function configures the interrupt. See the list
of interrupts below to see how _config_ is interpreted. Note that most
interrupts do not need configuration.

The *interrupt_isr*() function maps the interrupt to its _isr_. If _isr_
is NULL, no action is performed when that interrupt is raised, other
than acknowledging it.

The *interrupt_toggle*() function enables or disables the interrupt,
based on the value of _enable_.

The *interrupt_wait*() function waits for the interrupt to be raised,
then returns.

=== Interrupts
Interrupts are identified by the constants described below.

*IRQ_VBLANK*::
Periodically raised at the start of VBlank, after the last visible row
of pixels is rendered, with an approximate frequency of 59.73 Hz.

*IRQ_HBLANK*::
Periodically raised at the start of HBlank, after the last visible pixel
is rendered for each row (including hidden rows), with an approximate
frequency of 13.62 KHz.

*IRQ_VCOUNT*::
Periodically raised when a specific row of pixels begins being rendered,
with an approximate frequency of 59.73 Hz. The row can be selected by
calling *interrupt_config*() with _config_ in the range [0, 227].

*IRQ_TIMER0*, *IRQ_TIMER1*, *IRQ_TIMER2*, *IRQ_TIMER3*::
Raised when a timer's counter reaches zero. See *timer_config*(3).

*IRQ_DMA0*, *IRQ_DMA1*, *IRQ_DMA2*, *IRQ_DMA3*::
Raised when a DMA transfer is complete. See *dma_config*(3).

*IRQ_KEYPAD*::
TODO

*IRQ_GAMEPAK*::
Raised when the game cartridge is removed. Some cartridges may also
raise it to signal special events.

*IRQ_SERIAL*::
TODO

== NOTES
Each interrupt can only be mapped to one ISR at a time, meaning that
calling *interrupt_isr*() overwrites the previous association. If an
interrupt needs multiple ISRs, the recommended approach is to write a
wrapper function:

[source,c]
----
void foo_isr(void) {
    foo_isr_a();
    foo_isr_b();
}
----

== EXAMPLES
Enable the VBlank interrupt and map an ISR to it:

[source,c]
----
int AgbMain(void) {
    interrupt_isr(IRQ_VBLANK, vblank_isr);
    interrupt_toggle(IRQ_VBLANK, true);
}
----

== AUTHORS
The *libsimplegba* library was written by Vulcalien.
