#!/usr/bin/env python3

# Copyright 2026 Vulcalien
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

import argparse

parser = argparse.ArgumentParser(description='Verify ROM checksum')
parser.add_argument('file', type=argparse.FileType('rb'),
                    help='input ROM file')
args = parser.parse_args()

f = args.file
f.seek(160)
calculated = -(0x19 + sum(f.read(29))) & 0xff
found = f.read(1)[0]

print('Checksum: 0x%02x' % calculated)
print('Valid:    %s' % ('YES' if calculated == found else
                        'NO, found 0x%02x instead' % found))
